name: efpl
description: Ethiopian Fantasy Premier League.
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter
  intl: ^0.17.0
  flutter_bloc: ^8.0.1
  flutter_dotenv: ^5.0.2
  freezed_annotation: ^1.1.0
  get_it: ^7.2.0
  http: ^0.13.4
  http_interceptor: ^1.0.2
  injectable: ^1.5.3
  json_annotation: ^4.4.0
  shared_preferences: ^2.0.13
  material_design_icons_flutter: 5.0.6595
  flutter_boxicons: ^3.0.0
  flutter_svg: ^1.0.3
  flutter_secure_storage: ^5.0.2

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  freezed: ^1.0.9
  injectable_generator: ^1.4.9
  json_serializable: ^6.1.4
  lint: ^1.8.2
  mockito: ^5.1.0
  test: ^1.19.1

flutter:
  assets:
    - .env
    - assets/icons/
    - assets/img/
  fonts:
    - family: Architect
      fonts:
        - asset: fonts/ArchitectsDaughter-Regular.ttf
  uses-material-design: true
  generate: true
