name: efpl
description: Ethiopian Fantasy Premier League.
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_boxicons: ^3.0.0
  flutter_dotenv: ^5.0.2
  flutter_inset_box_shadow: ^1.0.8
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.0.3
  fluttericon: ^2.0.0
  freezed_annotation: ^1.1.0
  get_it: ^7.2.0
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  http: ^0.13.4
  http_interceptor: ^1.0.2
  injectable: ^1.5.3
  intl: ^0.17.0
  json_annotation: ^4.4.0
  liquid_pull_to_refresh: ^3.0.1
  material_design_icons_flutter: 5.0.6595
  path_provider: ^2.0.9
  shared_preferences: ^2.0.13
  socket_io_client: ^2.0.0-beta
  syncfusion_flutter_sliders: ^20.1.55
  tab_container: ^2.0.0
  transparent_image: ^2.0.0
  flutter_secure_storage: ^5.0.2
  showcaseview: ^1.1.5
  material_floating_search_bar: ^0.3.7

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  freezed: ^1.0.9
  hive_generator: ^1.1.2
  injectable_generator: ^1.4.9
  integration_test:
    sdk: flutter
  json_serializable: ^6.1.4
  lint: ^1.8.2
  mockito: ^5.1.0
  test: ^1.19.1

flutter:
  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/flags/
    - assets/teams/
    - assets/jerseys/
  fonts:
    - family: Architect
      fonts:
        - asset: assets/fonts/ArchitectsDaughter-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

  uses-material-design: true
  generate: true
