const playerInfo = {
  playerName: "Salamlak Tegegn",
  eplTeamId: "Bahir Dar Kenema S.C",
  currentPrice: 4.9,
  position: "DEF",
  availability: {
    injuryStatus: "25",
    injuryMessage: "Shoulder dislocations",
  },
  score: [
    {
      gameweekId: 1,
      price: 4.9,
      fantasyScore: 0,
      minutesPlayed: 0,
      goals: 0,
      assists: 0,
      cleanSheet: 0,
      yellows: 0,
      reds: 0,
      penalitiesMissed: 0,
      penalitiesSaved: 0,
      saves: 0,
      ownGoal: 0,
      transfersIn: 0,
      transfersOut: 0,
      form: 0,
    },
    {
      gameweekId: 2,
      price: 4.9,
      fantasyScore: 0,
      minutesPlayed: 0,
      goals: 0,
      assists: 0,
      cleanSheet: 0,
      yellows: 0,
      reds: 0,
      penalitiesMissed: 0,
      penalitiesSaved: 0,
      saves: 0,
      ownGoal: 0,
      transfersIn: 0,
      transfersOut: 0,
      form: 0,
    },
    {
      gameweekId: 3,
      price: 4.9,
      fantasyScore: 0,
      minutesPlayed: 0,
      goals: 0,
      assists: 0,
      cleanSheet: 0,
      yellows: 0,
      reds: 0,
      penalitiesMissed: 0,
      penalitiesSaved: 0,
      saves: 0,
      ownGoal: 0,
      transfersIn: 0,
      transfersOut: 0,
      form: 0,
    },
    {
      gameweekId: 4,
      price: 4.9,
      fantasyScore: 0,
      minutesPlayed: 0,
      goals: 0,
      assists: 0,
      cleanSheet: 0,
      yellows: 0,
      reds: 0,
      penalitiesMissed: 0,
      penalitiesSaved: 0,
      saves: 0,
      ownGoal: 0,
      transfersIn: 0,
      transfersOut: 0,
      form: 0,
    },
    {
      gameweekId: 5,
      price: 4.9,
      fantasyScore: 0,
      minutesPlayed: 0,
      goals: 0,
      assists: 0,
      cleanSheet: 0,
      yellows: 0,
      reds: 0,
      penalitiesMissed: 0,
      penalitiesSaved: 0,
      saves: 0,
      ownGoal: 0,
      transfersIn: 0,
      transfersOut: 0,
      form: 0,
    },
    {
      gameweekId: 6,
      price: 4.9,
      fantasyScore: 0,
      minutesPlayed: 0,
      goals: 0,
      assists: 0,
      cleanSheet: 0,
      yellows: 0,
      reds: 0,
      penalitiesMissed: 0,
      penalitiesSaved: 0,
      saves: 0,
      ownGoal: 0,
      transfersIn: 0,
      transfersOut: 0,
      form: 0,
    },
    {
      gameweekId: 7,
      price: 4.9,
      fantasyScore: 0,
      minutesPlayed: 0,
      goals: 0,
      assists: 0,
      cleanSheet: 0,
      yellows: 0,
      reds: 0,
      penalitiesMissed: 0,
      penalitiesSaved: 0,
      saves: 0,
      ownGoal: 0,
      transfersIn: 0,
      transfersOut: 0,
      form: 0,
    },
    {
      gameweekId: 8,
      price: 4.9,
      fantasyScore: 0,
      minutesPlayed: 0,
      goals: 0,
      assists: 0,
      cleanSheet: 0,
      yellows: 0,
      reds: 0,
      penalitiesMissed: 0,
      penalitiesSaved: 0,
      saves: 0,
      ownGoal: 0,
      transfersIn: 0,
      transfersOut: 0,
      form: 0,
    },
    {
      gameweekId: 9,
      price: 4.9,
      fantasyScore: 0,
      minutesPlayed: 0,
      goals: 0,
      assists: 0,
      cleanSheet: 0,
      yellows: 0,
      reds: 0,
      penalitiesMissed: 0,
      penalitiesSaved: 0,
      saves: 0,
      ownGoal: 0,
      transfersIn: 0,
      transfersOut: 0,
      form: 0,
    },
    {
      gameweekId: 10,
      price: 4.9,
      fantasyScore: 0,
      minutesPlayed: 0,
      goals: 0,
      assists: 0,
      cleanSheet: 0,
      yellows: 0,
      reds: 0,
      penalitiesMissed: 0,
      penalitiesSaved: 0,
      saves: 0,
      ownGoal: 0,
      transfersIn: 0,
      transfersOut: 0,
      form: 0,
    },
    {
      gameweekId: 11,
      price: 4.9,
      fantasyScore: 0,
      minutesPlayed: 0,
      goals: 0,
      assists: 0,
      cleanSheet: 0,
      yellows: 0,
      reds: 0,
      penalitiesMissed: 0,
      penalitiesSaved: 0,
      saves: 0,
      ownGoal: 0,
      transfersIn: 0,
      transfersOut: 0,
      form: 0,
    },
    {
      gameweekId: 12,
      price: 4.9,
      fantasyScore: 0,
      minutesPlayed: 0,
      goals: 0,
      assists: 0,
      cleanSheet: 0,
      yellows: 0,
      reds: 0,
      penalitiesMissed: 0,
      penalitiesSaved: 0,
      saves: 0,
      ownGoal: 0,
      transfersIn: 0,
      transfersOut: 0,
      form: 0,
    },
    {
      gameweekId: 13,
      price: 4.9,
      fantasyScore: 0,
      minutesPlayed: 0,
      goals: 0,
      assists: 0,
      cleanSheet: 0,
      yellows: 0,
      reds: 0,
      penalitiesMissed: 0,
      penalitiesSaved: 0,
      saves: 0,
      ownGoal: 0,
      transfersIn: 0,
      transfersOut: 0,
      form: 0,
    },
    {
      gameweekId: 14,
      price: 4.9,
      fantasyScore: 0,
      minutesPlayed: 0,
      goals: 0,
      assists: 0,
      cleanSheet: 0,
      yellows: 0,
      reds: 0,
      penalitiesMissed: 0,
      penalitiesSaved: 0,
      saves: 0,
      ownGoal: 0,
      transfersIn: 0,
      transfersOut: 0,
      form: 0,
    },
    {
      gameweekId: 15,
      price: 4.9,
      fantasyScore: 0,
      minutesPlayed: 0,
      goals: 0,
      assists: 0,
      cleanSheet: 0,
      yellows: 0,
      reds: 0,
      penalitiesMissed: 0,
      penalitiesSaved: 0,
      saves: 0,
      ownGoal: 0,
      transfersIn: 0,
      transfersOut: 0,
      form: 0,
    },
    {
      gameweekId: 16,
      price: 4.9,
      fantasyScore: 0,
      minutesPlayed: 0,
      goals: 0,
      assists: 0,
      cleanSheet: 0,
      yellows: 0,
      reds: 0,
      penalitiesMissed: 0,
      penalitiesSaved: 0,
      saves: 0,
      ownGoal: 0,
      transfersIn: 0,
      transfersOut: 0,
      form: 0,
    },
    {
      gameweekId: 17,
      price: 4.9,
      fantasyScore: 0,
      minutesPlayed: 0,
      goals: 0,
      assists: 0,
      cleanSheet: 0,
      yellows: 0,
      reds: 0,
      penalitiesMissed: 0,
      penalitiesSaved: 0,
      saves: 0,
      ownGoal: 0,
      transfersIn: 0,
      transfersOut: 0,
      form: 0,
    },
    {
      gameweekId: 18,
      price: 4.9,
      fantasyScore: 0,
      minutesPlayed: 0,
      goals: 0,
      assists: 0,
      cleanSheet: 0,
      yellows: 0,
      reds: 0,
      penalitiesMissed: 0,
      penalitiesSaved: 0,
      saves: 0,
      ownGoal: 0,
      transfersIn: 0,
      transfersOut: 0,
      form: 0,
    },
    {
      gameweekId: 19,
      price: 4.9,
      fantasyScore: 0,
      minutesPlayed: 0,
      goals: 0,
      assists: 0,
      cleanSheet: 0,
      yellows: 0,
      reds: 0,
      penalitiesMissed: 0,
      penalitiesSaved: 0,
      saves: 0,
      ownGoal: 0,
      transfersIn: 0,
      transfersOut: 0,
      form: 0,
    },
    {
      gameweekId: 20,
      price: 4.9,
      fantasyScore: 0,
      minutesPlayed: 0,
      goals: 0,
      assists: 0,
      cleanSheet: 0,
      yellows: 0,
      reds: 0,
      penalitiesMissed: 0,
      penalitiesSaved: 0,
      saves: 0,
      ownGoal: 0,
      transfersIn: 0,
      transfersOut: 0,
      form: 0,
    },
    {
      gameweekId: 21,
      price: 4.9,
      fantasyScore: 0,
      minutesPlayed: 0,
      goals: 0,
      assists: 0,
      cleanSheet: 0,
      yellows: 0,
      reds: 0,
      penalitiesMissed: 0,
      penalitiesSaved: 0,
      saves: 0,
      ownGoal: 0,
      transfersIn: 0,
      transfersOut: 0,
      form: 0,
    },
    {
      gameweekId: 22,
      price: 4.9,
      fantasyScore: 0,
      minutesPlayed: 0,
      goals: 0,
      assists: 0,
      cleanSheet: 0,
      yellows: 0,
      reds: 0,
      penalitiesMissed: 0,
      penalitiesSaved: 0,
      saves: 0,
      ownGoal: 0,
      transfersIn: 0,
      transfersOut: 0,
      form: 0,
    },
    {
      gameweekId: 23,
      price: 4.9,
      fantasyScore: 0,
      minutesPlayed: 0,
      goals: 0,
      assists: 0,
      cleanSheet: 0,
      yellows: 0,
      reds: 0,
      penalitiesMissed: 0,
      penalitiesSaved: 0,
      saves: 0,
      ownGoal: 0,
      transfersIn: 0,
      transfersOut: 0,
      form: 0,
    },
    {
      gameweekId: 24,
      price: 4.9,
      fantasyScore: 0,
      minutesPlayed: 0,
      goals: 0,
      assists: 0,
      cleanSheet: 0,
      yellows: 0,
      reds: 0,
      penalitiesMissed: 0,
      penalitiesSaved: 0,
      saves: 0,
      ownGoal: 0,
      transfersIn: 0,
      transfersOut: 0,
      form: 0,
    },
    {
      gameweekId: 25,
      price: 4.9,
      fantasyScore: 0,
      minutesPlayed: 0,
      goals: 0,
      assists: 0,
      cleanSheet: 0,
      yellows: 0,
      reds: 0,
      penalitiesMissed: 0,
      penalitiesSaved: 0,
      saves: 0,
      ownGoal: 0,
      transfersIn: 0,
      transfersOut: 0,
      form: 0,
    },
    {
      gameweekId: 26,
      price: 4.9,
      fantasyScore: 0,
      minutesPlayed: 0,
      goals: 0,
      assists: 0,
      cleanSheet: 0,
      yellows: 0,
      reds: 0,
      penalitiesMissed: 0,
      penalitiesSaved: 0,
      saves: 0,
      ownGoal: 0,
      transfersIn: 0,
      transfersOut: 0,
      form: 0,
    },
    {
      gameweekId: 27,
      price: 4.9,
      fantasyScore: 0,
      minutesPlayed: 0,
      goals: 0,
      assists: 0,
      cleanSheet: 0,
      yellows: 0,
      reds: 0,
      penalitiesMissed: 0,
      penalitiesSaved: 0,
      saves: 0,
      ownGoal: 0,
      transfersIn: 0,
      transfersOut: 0,
      form: 0,
    },
    {
      gameweekId: 28,
      price: 4.9,
      fantasyScore: 0,
      minutesPlayed: 0,
      goals: 0,
      assists: 0,
      cleanSheet: 0,
      yellows: 0,
      reds: 0,
      penalitiesMissed: 0,
      penalitiesSaved: 0,
      saves: 0,
      ownGoal: 0,
      transfersIn: 0,
      transfersOut: 0,
      form: 0,
    },
    {
      gameweekId: 29,
      price: 4.9,
      fantasyScore: 0,
      minutesPlayed: 0,
      goals: 0,
      assists: 0,
      cleanSheet: 0,
      yellows: 0,
      reds: 0,
      penalitiesMissed: 0,
      penalitiesSaved: 0,
      saves: 0,
      ownGoal: 0,
      transfersIn: 0,
      transfersOut: 0,
      form: 0,
    },
    {
      gameweekId: 30,
      price: 4.9,
      fantasyScore: 0,
      minutesPlayed: 0,
      goals: 0,
      assists: 0,
      cleanSheet: 0,
      yellows: 0,
      reds: 0,
      penalitiesMissed: 0,
      penalitiesSaved: 0,
      saves: 0,
      ownGoal: 0,
      transfersIn: 0,
      transfersOut: 0,
      form: 0,
    },
  ],
  history: [],
};

module.exports = { playerInfo };
