// eslint-disable-next-line no-unused-vars
const x = {
  activeChip: "",
  gameweekId: 1,
  players: {
    100026: {
      playerId: "100026",
      eplTeamId: "Bahir Dar Kenema S.C",
      price: 5,
      multiplier: 0,
      isCaptain: false,
      isViceCaptain: false,
    },
    100030: {
      playerId: "100030",
      eplTeamId: "Bahir Dar Kenema S.C",
      price: 5.5,
      multiplier: 0,
      isCaptain: false,
      isViceCaptain: false,
    },
    100031: {
      playerId: "100031",
      eplTeamId: "Bahir Dar Kenema S.C",
      price: 5,
      multiplier: 0,
      isCaptain: false,
      isViceCaptain: false,
    },
    100153: {
      playerId: "100153",
      eplTeamId: "Addis Ababa City F.C",
      price: 4.6,
      multiplier: 0,
      isCaptain: false,
      isViceCaptain: false,
    },
    100158: {
      playerId: "100158",
      eplTeamId: "Addis Ababa City F.C",
      price: 4.9,
      multiplier: 0,
      isCaptain: false,
      isViceCaptain: false,
    },
    100159: {
      playerId: "100159",
      eplTeamId: "Addis Ababa City F.C",
      price: 4.7,
      multiplier: 0,
      isCaptain: false,
      isViceCaptain: false,
    },
    100313: {
      playerId: "100313",
      eplTeamId: "Hawassa Kenema S.C",
      price: 4,
      multiplier: 0,
      isCaptain: false,
      isViceCaptain: false,
    },
    100336: {
      playerId: "100336",
      eplTeamId: "Fasil Kenema S.C",
      price: 4,
      multiplier: 0,
      isCaptain: false,
      isViceCaptain: false,
    },
    100338: {
      playerId: "100338",
      eplTeamId: "Fasil Kenema S.C",
      price: 4,
      multiplier: 0,
      isCaptain: false,
      isViceCaptain: false,
    },
    100401: {
      playerId: "100401",
      eplTeamId: "Adama City S.C",
      price: 6,
      multiplier: 0,
      isCaptain: false,
      isViceCaptain: false,
    },
    100402: {
      playerId: "100402",
      eplTeamId: "Adama City S.C",
      price: 6,
      multiplier: 0,
      isCaptain: false,
      isViceCaptain: false,
    },
    100431: {
      playerId: "100431",
      eplTeamId: "Adama City S.C",
      price: 6,
      multiplier: 0,
      isCaptain: false,
      isViceCaptain: false,
    },
    100441: {
      playerId: "100441",
      eplTeamId: "Arba Minch City F.C",
      price: 6,
      multiplier: 0,
      isCaptain: false,
      isViceCaptain: false,
    },
    100453: {
      playerId: "100453",
      eplTeamId: "Arba Minch City F.C",
      price: 6,
      multiplier: 0,
      isCaptain: false,
      isViceCaptain: false,
    },
    100455: {
      playerId: "100455",
      eplTeamId: "Arba Minch City F.C",
      price: 6,
      multiplier: 0,
      isCaptain: false,
      isViceCaptain: false,
    },
  },
};
